version: '3.6'

services:

  mysql1:
    container_name: spreadshare-mysql-testing
    build: docker-testing/mysql
    restart: always
    hostname: mysql1
    expose:
      - "3306"
    ports:
      - "3308:3306"
    volumes:
      - ./docker-testing/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./schemas/structure.sql:/docker-entrypoint-initdb.d/01_structure.sql
    env_file:
        - docker-testing/variables.env

  memcached:
    container_name: spreadshare-memcached-testing
    restart: always
    hostname: memcached
    image: memcached:1.5.2
    ports:
      - "11212:11211"

  redis:
    container_name: spreadshare-redis-testing
    restart: always
    hostname: redis
    image: redis:4.0
    ports:
      - "6380:6379"
    volumes:
      - redis:/data

  elasticsearch:
    container_name: spreadshare-elastic-testing
    image: elasticsearch:5
    restart: always
    expose:
      - "9200"
      - "9300"
    ports:
      - "9201:9200"
      - "9301:9300"
    env_file:
      - docker-testing/variables.env

  app:
    build: docker-testing/app
    container_name: spreadshare-backend-testing
    restart: always
    hostname: spreadshare
    working_dir: /project
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - .:/project/application
      - ./docker-testing/conf/php/cli.ini:/etc/php/7.0/cli/conf.d/100-custom.ini
      - ./docker-testing/conf/php/fpm.ini:/etc/php/7.0/fpm/conf.d/100-custom.ini
      - ./docker-testing/apache2:/etc/apache2/spreadshare
    depends_on:
      - mysql1
      - redis
      - memcached
      - elasticsearch
    env_file:
      - docker-testing/variables.env
    environment:
        BUILD_ENVIRONMENT: 'development'
        APPLICATION_ENV: 'development'
        HOST: 'spreadshare.javisantos.com:81'
        AUTH_CALLBACK: 'http://spreadshare.javisantos.com:811/login'
        WALLET: 'localhost'
        MAILGUN_KEY: 'key-611a7bf686cb890b8db38ad9ce1a5bbb'
        CRYPT_KEY: "iuh213iu78ads898213euwioadjbxhjy-jkldHJKDJ_ksahdKASGDS\$AKDH32L4EJLDSACKÖÄASPOE24"
        SENTRY_KEY: 'https://fcdde304c3344126b70b8f8365df7650:1ef8823d9153412a9f77250fa9d45235@sentry.io/240812'
        SLACK_WEBHOOK: 'https://hooks.slack.com/services/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'
        FILES_SERVICE: 'local'
        AUTH_DEBUG: '1'
        TWITTER_ID: '764738293347024896'
        TWITTER_KEY: 'G6PfK0VGgF1GFYROic4hSAcAr'
        TWITTER_SECRET: 'imPH3BmKlk3XWzKY2DrcAXbll329NNwASRxgLK1Fw52pns2oGP'
        GOOGLE_ID: '1069128037243-4cua499nu3jf64l2q4irms93pmh7trsk.apps.googleusercontent.com'
        GOOGLE_SECRET: 'd59PePUgDSCGgB_JuxGerScB'
        FACEBOOK_ID: '153117502101937'
        FACEBOOK_SECRET: 'f1c03b95bfc5c671085147b31b0474ef'

volumes:
  redis:
    driver: local
