<?php

namespace DS\Model\Abstracts;

/**
 * AbstractUserStats
 * 
 * @package DS\Model\Abstracts
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-11-08, 17:05:52
 */
abstract class AbstractUserStats extends \DS\Model\Base
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $id;

    /**
     *
     * @var integer
     * @Column(type="integer", length=11, nullable=true)
     */
    protected $userId;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    protected $tablesOwnerCount;

    /**
     *
     * @var integer
     * @Column(type="integer", length=10, nullable=true)
     */
    protected $rowsOwnerCount;

    /**
     * Method to set the value of field id
     *
     * @param integer $id
     * @return $this
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Method to set the value of field userId
     *
     * @param integer $userId
     * @return $this
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * Method to set the value of field tablesOwnerCount
     *
     * @param integer $tablesOwnerCount
     * @return $this
     */
    public function setTablesOwnerCount($tablesOwnerCount)
    {
        $this->tablesOwnerCount = $tablesOwnerCount;

        return $this;
    }

    /**
     * Method to set the value of field rowsOwnerCount
     *
     * @param integer $rowsOwnerCount
     * @return $this
     */
    public function setRowsOwnerCount($rowsOwnerCount)
    {
        $this->rowsOwnerCount = $rowsOwnerCount;

        return $this;
    }

    /**
     * Returns the value of field id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns the value of field userId
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Returns the value of field tablesOwnerCount
     *
     * @return integer
     */
    public function getTablesOwnerCount()
    {
        return $this->tablesOwnerCount;
    }

    /**
     * Returns the value of field rowsOwnerCount
     *
     * @return integer
     */
    public function getRowsOwnerCount()
    {
        return $this->rowsOwnerCount;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("spreadshare");
        $this->setSource("userStats");
        $this->belongsTo('userId', 'DS\Model\Abstracts\User', 'id', ['alias' => 'User']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'userStats';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return AbstractUserStats[]|AbstractUserStats|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return AbstractUserStats|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
