<?php

namespace DS\Model\Abstracts;

/**
 * AbstractTableProperties
 * 
 * @package DS\Model\Abstracts
 * @autogenerated by Phalcon Developer Tools
 * @date 2017-12-06, 10:12:53
 */
abstract class AbstractTableProperties extends \DS\Model\Base
{

    /**
     *
     * @var integer
     * @Primary
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $tableId;

    /**
     *
     * @var integer
     * @Column(type="integer", length=9, nullable=true)
     */
    protected $fixedRowsTop;

    /**
     *
     * @var integer
     * @Column(type="integer", length=9, nullable=true)
     */
    protected $fixedColumnsLeft;

    /**
     * Method to set the value of field tableId
     *
     * @param integer $tableId
     * @return $this
     */
    public function setTableId($tableId)
    {
        $this->tableId = $tableId;

        return $this;
    }

    /**
     * Method to set the value of field fixedRowsTop
     *
     * @param integer $fixedRowsTop
     * @return $this
     */
    public function setFixedRowsTop($fixedRowsTop)
    {
        $this->fixedRowsTop = $fixedRowsTop;

        return $this;
    }

    /**
     * Method to set the value of field fixedColumnsLeft
     *
     * @param integer $fixedColumnsLeft
     * @return $this
     */
    public function setFixedColumnsLeft($fixedColumnsLeft)
    {
        $this->fixedColumnsLeft = $fixedColumnsLeft;

        return $this;
    }

    /**
     * Returns the value of field tableId
     *
     * @return integer
     */
    public function getTableId()
    {
        return $this->tableId;
    }

    /**
     * Returns the value of field fixedRowsTop
     *
     * @return integer
     */
    public function getFixedRowsTop()
    {
        return $this->fixedRowsTop;
    }

    /**
     * Returns the value of field fixedColumnsLeft
     *
     * @return integer
     */
    public function getFixedColumnsLeft()
    {
        return $this->fixedColumnsLeft;
    }

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("spreadshare");
        $this->setSource("tableProperties");
        $this->belongsTo('tableId', 'DS\Model\Abstracts\Tables', 'id', ['alias' => 'Tables']);
    }

    /**
     * Returns table name mapped in the model.
     *
     * @return string
     */
    public function getSource()
    {
        return 'tableProperties';
    }

    /**
     * Allows to query a set of records that match the specified conditions
     *
     * @param mixed $parameters
     * @return AbstractTableProperties[]|AbstractTableProperties|\Phalcon\Mvc\Model\ResultSetInterface
     */
    public static function find($parameters = null)
    {
        return parent::find($parameters);
    }

    /**
     * Allows to query the first record that match the specified conditions
     *
     * @param mixed $parameters
     * @return AbstractTableProperties|\Phalcon\Mvc\Model\ResultInterface
     */
    public static function findFirst($parameters = null)
    {
        return parent::findFirst($parameters);
    }

}
